### ISSUE TITLE
Add CSS

### ISSUE THREAD

**Issue by SrushtiPatiL25** [Keyurkolambe/Covid-19-Tracker#1]
Hey, 
I think adding CSS would beautify HTML. 
Can you assign me that work?

**Comment by Shubham56-droid** [comment]
pls assign the issue to i can add css with good animation

**Comment by Shubham56-droid** [comment]
also, i will also add glass morphism  to make  it  look  awesome

**Comment by Shubham56-droid** [comment]
i will also add few  CSS property so it will become responsive  in  mobile  phone tablets  and other devices
